In [2]:
%pip install requests pandas

Requirement already satisfied: requests in ./venv/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: pandas in ./venv/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.13/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.13/site-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.13/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.13/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import requests
import pandas as pd

BASE_URL = "https://api.met.gov.my/v2.1"
TOKEN = "800b8992bc918dff3b95348ea036e3cf2837b92c"

headers = {
    "Authorization": f"METToken {TOKEN}"
}

location_category = "TOWN"
offset = 0

url = f"{BASE_URL}/locations"
params = {
    "locationcategoryid": location_category,
    "offset": offset
}

response = requests.get(url, headers=headers, params=params)

print("Status Code:", response.status_code)

data = response.json()
data

Status Code: 200

{'metadata': {'resultset': {'count': 154,
   'offset': 0,
   'limit': 50,
   'locationcategoryid': 'TOWN'}},
 'results': [{'id': 'LOCATION:127',
   'name': 'MUAR',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.0442,
   'longitude': 102.5689},
  {'id': 'LOCATION:126',
   'name': 'TANGKAK',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.2673,
   'longitude': 102.5453},
  {'id': 'LOCATION:125',
   'name': 'LABIS',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.385,
   'longitude': 103.021},
  {'id': 'LOCATION:124',
   'name': 'JOHOR BAHRU',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.4655,
   'longitude': 103.7578},
  {'id': 'LOCATION:122',
   'name': 'AYER HITAM',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.915,
   'longitude': 103.1808},
  {'id': 'LOCATION:123',
   'name': 'BATU PAHAT',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.8548,
   'longitude': 102.9325},
  {'id': 'LOCATION:131',
   'name': 'MERSING',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.4312,
   'longitude': 103.8405},
  {'id': 'LOCATION:659',
   'name': 'ISKANDAR PUTERI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.4135905,
   'longitude': 103.6317194},
  {'id': 'LOCATION:129',
   'name': 'KLUANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.0251,
   'longitude': 103.3328},
  {'id': 'LOCATION:768',
   'name': 'NUSAJAYA',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.4239,
   'longitude': 103.6485},
  {'id': 'LOCATION:130',
   'name': 'KOTA TINGGI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.7381,
   'longitude': 103.8999},
  {'id': 'LOCATION:134',
   'name': 'PONTIAN',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.5,
   'longitude': 103.5},
  {'id': 'LOCATION:135',
   'name': 'SEGAMAT',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.5148,
   'longitude': 102.8158},
  {'id': 'LOCATION:136',
   'name': 'SENAI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.64131,
   'longitude': 103.66962},
  {'id': 'LOCATION:137',
   'name': 'SIMPANG RENGGAM',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.825,
   'longitude': 103.3107},
  {'id': 'LOCATION:138',
   'name': 'YONG PENG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.0136,
   'longitude': 103.0659},
  {'id': 'LOCATION:133',
   'name': 'PASIR GUDANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.462,
   'longitude': 103.9053},
  {'id': 'LOCATION:439',
   'name': 'KULAI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 1.532949,
   'longitude': 103.6450341},
  {'id': 'LOCATION:128',
   'name': 'PAGOH',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:1',
   'latitude': 2.1495,
   'longitude': 102.7704},
  {'id': 'LOCATION:426',
   'name': 'SERDANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 5.2093299,
   'longitude': 100.6119237},
  {'id': 'LOCATION:139',
   'name': 'ALOR STAR',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 6.12104,
   'longitude': 100.36014},
  {'id': 'LOCATION:140',
   'name': 'BALING',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 5.67806,
   'longitude': 100.9177},
  {'id': 'LOCATION:141',
   'name': 'JITRA',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 6.26812,
   'longitude': 100.42167},
  {'id': 'LOCATION:142',
   'name': 'KUALA NERANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 6.25844,
   'longitude': 100.61264},
  {'id': 'LOCATION:143',
   'name': 'KULIM',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 5.32403,
   'longitude': 100.60851},
  {'id': 'LOCATION:145',
   'name': 'PENDANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 5.98458,
   'longitude': 100.60732},
  {'id': 'LOCATION:146',
   'name': 'POKOK SENA',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 6.17055,
   'longitude': 100.51885},
  {'id': 'LOCATION:147',
   'name': 'SIK',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 6.03482,
   'longitude': 100.8603},
  {'id': 'LOCATION:148',
   'name': 'SUNGAI PETANI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 5.647,
   'longitude': 100.48772},
  {'id': 'LOCATION:149',
   'name': 'YAN',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:2',
   'latitude': 5.7905,
   'longitude': 100.39426},
  {'id': 'LOCATION:154',
   'name': 'KUALA KRAI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 5.5313,
   'longitude': 102.19925},
  {'id': 'LOCATION:155',
   'name': 'LOJING',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 4.7046137,
   'longitude': 101.5553148},
  {'id': 'LOCATION:156',
   'name': 'MACHANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 5.76407,
   'longitude': 102.21414},
  {'id': 'LOCATION:158',
   'name': 'PASIR PUTEH',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 5.83333,
   'longitude': 102.4},
  {'id': 'LOCATION:160',
   'name': 'TANAH MERAH',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 5.66667,
   'longitude': 102.0},
  {'id': 'LOCATION:161',
   'name': 'TUMPAT',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 6.19776,
   'longitude': 102.17098},
  {'id': 'LOCATION:153',
   'name': 'KOTA BHARU',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 6.05666,
   'longitude': 102.26451},
  {'id': 'LOCATION:152',
   'name': 'JELI',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 5.71493,
   'longitude': 101.88418},
  {'id': 'LOCATION:151',
   'name': 'GUA MUSANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 4.8823,
   'longitude': 101.9644},
  {'id': 'LOCATION:150',
   'name': 'BACHOK',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 6.06667,
   'longitude': 102.4},
  {'id': 'LOCATION:159',
   'name': 'RANTAU PANJANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 6.021325,
   'longitude': 101.9732687},
  {'id': 'LOCATION:157',
   'name': 'PASIR MAS',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:3',
   'latitude': 6.0424976,
   'longitude': 102.1427782},
  {'id': 'LOCATION:169',
   'name': 'SETAPAK',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.18333,
   'longitude': 101.7},
  {'id': 'LOCATION:340',
   'name': 'KUALA LUMPUR',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.1429996,
   'longitude': 101.6947998},
  {'id': 'LOCATION:162',
   'name': 'AMPANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.15,
   'longitude': 101.76667},
  {'id': 'LOCATION:163',
   'name': 'BANGSAR',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.12222,
   'longitude': 101.67606},
  {'id': 'LOCATION:164',
   'name': 'BUKIT BINTANG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 5.63052,
   'longitude': 102.6479},
  {'id': 'LOCATION:165',
   'name': 'CHERAS',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.05,
   'longitude': 101.76667},
  {'id': 'LOCATION:166',
   'name': 'JALAN DUTA',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.1484,
   'longitude': 101.6779},
  {'id': 'LOCATION:167',
   'name': 'KEPONG',
   'locationcategoryid': 'TOWN',
   'locationrootid': 'LOCATION:4',
   'latitude': 3.21667,
   'longitude': 101.63333}]}

In [4]:
results = data.get("results", [])
df_locations = pd.json_normalize(results)

df_locations

,id,name,locationcategoryid,locationrootid,latitude,longitude
0,LOCATION:127,MUAR,TOWN,LOCATION:1,2.044200,102.568900
1,LOCATION:126,TANGKAK,TOWN,LOCATION:1,2.267300,102.545300
2,LOCATION:125,LABIS,TOWN,LOCATION:1,2.385000,103.021000
3,LOCATION:124,JOHOR BAHRU,TOWN,LOCATION:1,1.465500,103.757800
4,LOCATION:122,AYER HITAM,TOWN,LOCATION:1,1.915000,103.180800
5,LOCATION:123,BATU PAHAT,TOWN,LOCATION:1,1.854800,102.932500
6,LOCATION:131,MERSING,TOWN,LOCATION:1,2.431200,103.840500
7,LOCATION:659,ISKANDAR PUTERI,TOWN,LOCATION:1,1.413590,103.631719
8,LOCATION:129,KLUANG,TOWN,LOCATION:1,2.025100,103.332800
9,LOCATION:768,NUSAJAYA,TOWN,LOCATION:1,1.423900,103.648500
10,LOCATION:130,KOTA TINGGI,TOWN,LOCATION:1,1.738100,103.899900
11,LOCATION:134,PONTIAN,TOWN,LOCATION:1,1.500000,103.500000
12,LOCATION:135,SEGAMAT,TOWN,LOCATION:1,2.514800,102.815800
13,LOCATION:136,SENAI,TOWN,LOCATION:1,1.641310,103.669620
14,LOCATION:137,SIMPANG RENGGAM,TOWN,LOCATION:1,1.825000,103.310700
15,LOCATION:138,YONG PENG,TOWN,LOCATION:1,2.013600,103.065900
16,LOCATION:133,PASIR GUDANG,TOWN,LOCATION:1,1.462000,103.905300
17,LOCATION:439,KULAI,TOWN,LOCATION:1,1.532949,103.645034
18,LOCATION:128,PAGOH,TOWN,LOCATION:1,2.149500,102.770400
19,LOCATION:426,SERDANG,TOWN,LOCATION:2,5.209330,100.611924
20,LOCATION:139,ALOR STAR,TOWN,LOCATION:2,6.121040,100.360140
21,LOCATION:140,BALING,TOWN,LOCATION:2,5.678060,100.917700
22,LOCATION:141,JITRA,TOWN,LOCATION:2,6.268120,100.421670
23,LOCATION:142,KUALA NERANG,TOWN,LOCATION:2,6.258440,100.612640
24,LOCATION:143,KULIM,TOWN,LOCATION:2,5.324030,100.608510
25,LOCATION:145,PENDANG,TOWN,LOCATION:2,5.984580,100.607320
26,LOCATION:146,POKOK SENA,TOWN,LOCATION:2,6.170550,100.518850
27,LOCATION:147,SIK,TOWN,LOCATION:2,6.034820,100.860300
28,LOCATION:148,SUNGAI PETANI,TOWN,LOCATION:2,5.647000,100.487720
29,LOCATION:149,YAN,TOWN,LOCATION:2,5.790500,100.394260
30,LOCATION:154,KUALA KRAI,TOWN,LOCATION:3,5.531300,102.199250
31,LOCATION:155,LOJING,TOWN,LOCATION:3,4.704614,101.555315
32,LOCATION:156,MACHANG,TOWN,LOCATION:3,5.764070,102.214140
33,LOCATION:158,PASIR PUTEH,TOWN,LOCATION:3,5.833330,102.400000
34,LOCATION:160,TANAH MERAH,TOWN,LOCATION:3,5.666670,102.000000
35,LOCATION:161,TUMPAT,TOWN,LOCATION:3,6.197760,102.170980
36,LOCATION:153,KOTA BHARU,TOWN,LOCATION:3,6.056660,102.264510
37,LOCATION:152,JELI,TOWN,LOCATION:3,5.714930,101.884180
38,LOCATION:151,GUA MUSANG,TOWN,LOCATION:3,4.882300,101.964400
39,LOCATION:150,BACHOK,TOWN,LOCATION:3,6.066670,102.400000
40,LOCATION:159,RANTAU PANJANG,TOWN,LOCATION:3,6.021325,101.973269
41,LOCATION:157,PASIR MAS,TOWN,LOCATION:3,6.042498,102.142778
42,LOCATION:169,SETAPAK,TOWN,LOCATION:4,3.183330,101.700000
43,LOCATION:340,KUALA LUMPUR,TOWN,LOCATION:4,3.143000,101.694800
44,LOCATION:162,AMPANG,TOWN,LOCATION:4,3.150000,101.766670
45,LOCATION:163,BANGSAR,TOWN,LOCATION:4,3.122220,101.676060
46,LOCATION:164,BUKIT BINTANG,TOWN,LOCATION:4,5.630520,102.647900
47,LOCATION:165,CHERAS,TOWN,LOCATION:4,3.050000,101.766670
48,LOCATION:166,JALAN DUTA,TOWN,LOCATION:4,3.148400,101.677900
49,LOCATION:167,KEPONG,TOWN,LOCATION:4,3.216670,101.633330

In [5]:
df_locations.columns.tolist()

['id', 'name', 'locationcategoryid', 'locationrootid', 'latitude', 'longitude']

In [6]:
useful_cols = [col for col in [
    "locationid",
    "locationname",
    "locationcategoryid",
    "latitude",
    "longitude",
    "locationrootid",
    "locationrootname"
] if col in df_locations.columns]

df_locations[useful_cols]

   locationcategoryid  latitude   longitude locationrootid
0                TOWN  2.044200  102.568900     LOCATION:1
1                TOWN  2.267300  102.545300     LOCATION:1
2                TOWN  2.385000  103.021000     LOCATION:1
3                TOWN  1.465500  103.757800     LOCATION:1
4                TOWN  1.915000  103.180800     LOCATION:1
5                TOWN  1.854800  102.932500     LOCATION:1
6                TOWN  2.431200  103.840500     LOCATION:1
7                TOWN  1.413590  103.631719     LOCATION:1
8                TOWN  2.025100  103.332800     LOCATION:1
9                TOWN  1.423900  103.648500     LOCATION:1
10               TOWN  1.738100  103.899900     LOCATION:1
11               TOWN  1.500000  103.500000     LOCATION:1
12               TOWN  2.514800  102.815800     LOCATION:1
13               TOWN  1.641310  103.669620     LOCATION:1
14               TOWN  1.825000  103.310700     LOCATION:1
15               TOWN  2.013600  103.065900     LOCATION:1
16               TOWN  1.462000  103.905300     LOCATION:1
17               TOWN  1.532949  103.645034     LOCATION:1
18               TOWN  2.149500  102.770400     LOCATION:1
19               TOWN  5.209330  100.611924     LOCATION:2
20               TOWN  6.121040  100.360140     LOCATION:2
21               TOWN  5.678060  100.917700     LOCATION:2
22               TOWN  6.268120  100.421670     LOCATION:2
23               TOWN  6.258440  100.612640     LOCATION:2
24               TOWN  5.324030  100.608510     LOCATION:2
25               TOWN  5.984580  100.607320     LOCATION:2
26               TOWN  6.170550  100.518850     LOCATION:2
27               TOWN  6.034820  100.860300     LOCATION:2
28               TOWN  5.647000  100.487720     LOCATION:2
29               TOWN  5.790500  100.394260     LOCATION:2
30               TOWN  5.531300  102.199250     LOCATION:3
31               TOWN  4.704614  101.555315     LOCATION:3
32               TOWN  5.764070  102.214140     LOCATION:3
33               TOWN  5.833330  102.400000     LOCATION:3
34               TOWN  5.666670  102.000000     LOCATION:3
35               TOWN  6.197760  102.170980     LOCATION:3
36               TOWN  6.056660  102.264510     LOCATION:3
37               TOWN  5.714930  101.884180     LOCATION:3
38               TOWN  4.882300  101.964400     LOCATION:3
39               TOWN  6.066670  102.400000     LOCATION:3
40               TOWN  6.021325  101.973269     LOCATION:3
41               TOWN  6.042498  102.142778     LOCATION:3
42               TOWN  3.183330  101.700000     LOCATION:4
43               TOWN  3.143000  101.694800     LOCATION:4
44               TOWN  3.150000  101.766670     LOCATION:4
45               TOWN  3.122220  101.676060     LOCATION:4
46               TOWN  5.630520  102.647900     LOCATION:4
47               TOWN  3.050000  101.766670     LOCATION:4
48               TOWN  3.148400  101.677900     LOCATION:4
49               TOWN  3.216670  101.633330     LOCATION:4

In [7]:
def get_all_locations(location_category: str, token: str) -> pd.DataFrame:
    base_url = "https://api.met.gov.my/v2.1/locations"
    headers = {
        "Authorization": f"METToken {token}"
    }

    all_results = []
    offset = 0
    page_size = 50

    while True:
        params = {
            "locationcategoryid": location_category,
            "offset": offset
        }

        response = requests.get(base_url, headers=headers, params=params)
        response.raise_for_status()

        data = response.json()
        results = data.get("results", [])

        if not results:
            break

        all_results.extend(results)

        print(f"Fetched {len(results)} records at offset={offset}")

        if len(results) < page_size:
            break

        offset += page_size

    return pd.json_normalize(all_results)

In [ ]:
df_town_locations = get_all_locations("TOWN", TOKEN)

# df_town_locations.head()
df_town_locations

Fetched 50 records at offset=0
Fetched 50 records at offset=50